name: notely
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  smooth_page_indicator: ^1.2.1
  go_router: ^16.0.0
  firebase_core: ^2.27.0
  firebase_auth: ^4.18.0
  google_sign_in: ^6.2.1
  cloud_firestore: ^4.15.9
  toast: ^0.3.0
  uuid: ^4.4.1
  get_it: ^8.0.3
  injectable: ^2.5.0
  provider: ^6.1.5
  dio: ^5.8.0+1
  shared_preferences: ^2.5.3
  date_format: ^2.0.9
  intl: ^0.18.1
  flutter_local_notifications: ^19.4.1
  timezone: ^0.10.1
  flutter_timezone: ^4.1.1
  http: ^1.5.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.4
  injectable_generator: ^2.7.0



  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
     - assets/images/get_started_first_image.png
     - assets/images/google.png
     - assets/images/apple.png
     - assets/images/writing.png
     - assets/images/facebook.png
     - assets/images/notely_sucess.png


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
