// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
// / import 'firebase_options.dart';
// / // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAqI2vGqGGYbCtLYPe57Wu9Saxo9wFJ8jc',
    appId: '1:697202726960:android:95a40ae05de851cffaf5f5',
    messagingSenderId: '697202726960',
    projectId: 'notely-a470d',
    storageBucket: 'notely-a470d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8FrDRwn2Pu3QoNvlqrzjvtHzQ9ZiUWWk',
    appId: '1:697202726960:ios:42596e3034ad6e26faf5f5',
    messagingSenderId: '697202726960',
    projectId: 'notely-a470d',
    storageBucket: 'notely-a470d.firebasestorage.app',
    iosBundleId: 'com.example.notely',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8FrDRwn2Pu3QoNvlqrzjvtHzQ9ZiUWWk',
    appId: '1:697202726960:ios:42596e3034ad6e26faf5f5',
    messagingSenderId: '697202726960',
    projectId: 'notely-a470d',
    storageBucket: 'notely-a470d.firebasestorage.app',
    iosBundleId: 'com.example.notely',
  );
}
